### PR TITLE
Fallback Enum class and boolean index fix

### LINKED ISSUE #34: Cannot index with booleans
```python
import arrayfire
a = arrayfire.randu(3)
b = arrayfire.constant(1,3,dtype=arrayfire.Dtype.b8)
a[b] = 1
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-64b55ef890aa> in <module>()
----> 1 a[b] = 1

/Users/filipe/Library/Python/2.7/lib/python/site-packages/arrayfire-3.0.0-py2.7.egg/arrayfire/array.pyc in __setitem__(self, key, val)
    908
    909         except RuntimeError as e:
--> 910             raise IndexError(str(e))
    911
    912     def to_ctype(self, row_major=False, return_shape=False):

IndexError: ('In function /Users/filipe/src/arrayfire/src/api/c/assign.cpp(272):\nInvalid argument at index 3\nExpected: (idxType!=b8 )\n', 202)
```

This works in C++, but not in C, that's why the error. I think it would be more user friendly if it worked also in C.

Here's the C++ example showing the issue in arrayfire:

```c++
#include <arrayfire.h>

int main(){
  af::array a = af::randu(3);
  af::array idx = af::constant(1,3,b8);
  af_print(a(idx));
  af_index_t c_idx;
  c_idx.idx.arr = idx.get();
  c_idx.isSeq = false;
  c_idx.isBatch = false;   
  af_array ret;
  af_err err = af_index_gen(&ret, a.get(), 1, &c_idx);
  char * str;
  dim_t strlen;
  af_get_last_error(&str, &strlen);
  printf("%s\n", str);
}
```

### PR DESCRIPTION
**Pull request by pavanky**
- Fixes #34

### CODE REVIEW

**Comment by FilipeMaia** [comment]
The name `Enum_value` does not match the other functions. Its use also looks a bit clunky...

**Comment by pavanky** [comment]
@FilipeMaia `Enum_value` is a place holder for now. It is easy to grep and replace for any future changes.

**Comment by FilipeMaia** [comment]
Instead of having an Enum_value causing changes all over the code what about changing the way the enums are defined, e.g.:

```python
try:
    from enum import Enum    
    def EnumType(v):
        return v
except:
    class Enum(object):
        pass
    class EnumType(object):
        def __init__(self, v):
            self.value = v

class Dtype(Enum):
    """
    Error values. For internal use only.
    """
    f32 = EnumType(0)
    ...
```

That way all the changes would be in the same place.

**Comment by pavanky** [comment]
@FilipeMaia That would work.

**Comment by pavanky** [comment]
Fixed the Enum class, looking into the Index class issue.

**Comment by pavanky** [comment]
Welp, its broken. Fixing hit.

**Comment by pavanky** [comment]
Accidentally pushed to upstream :( I will fix the index issue in upstream shortly.

**Comment by FilipeMaia** [comment]
Ok

**Pull request closed without merging**
