### PR TITLE
add short types

### PR DESCRIPTION
**Pull request by aha66**

### CODE REVIEW

**Comment by pavanky** [comment]
@aha66 can you add some naive tests to `tests/simple/array_test.py` where you create s16 / u16 arrays and get them back to host ?

**Comment by aha66** [comment]
@pavanky ok :) - I'll do so within the next days

**Comment by pavanky** [comment]
@aha66 If you are busy I can merge your PR and add the tests myself then :)

**Comment by aha66** [comment]
@pavanky this would be fine - thanks!

**Pull request merged**
